local:             &local
  secret_key_base: '5c1e90004cc45358eac49153e427ba278087c7c9be7a0b7c88cf6cd42eaaf22ab245023930eb77cc2239ae97ca435d00f9b24223b85da5017c289f9b46e7befe'

test:
  <<:              *local

development:
  <<:              *local


deployed:          &deployed
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  <<:              *deployed

production:
  <<:              *deployed

pentest:
  <<:              *deployed
